describe("guess number", function () {
    function mock_generate_random_number() {
        return 1234;
    }

    beforeEach(function () {
        guess_obj = new Guess(mock_generate_random_number);
    });

    it("given a 1234, when guess the 1234 generated by mock_generate_random_number, then it should return 4A0B", function () {
        var given_number = 1234;

        var result = guess_obj.guess_number(given_number);

        expect(result).toBe("4A0B");
    });
});